interface Coin {
  id: string;
  name: string;
  symbol: string;
  price: number;
  change: string;
  up: boolean;
}

export const localCoins: any = [
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'btc',
    price: 65000,
    change: '+2.35%',
    up: true,
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'eth',
    price: 3200,
    change: '-1.20%',
    up: false,
  },
  {
    id: 'tether',
    name: 'Tether',
    symbol: 'usdt',
    price: 1,
    change: '+0.01%',
    up: true,
  },
  {
    id: 'binancecoin',
    name: 'BNB',
    symbol: 'bnb',
    price: 420,
    change: '+0.85%',
    up: true,
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'sol',
    price: 150,
    change: '-0.50%',
    up: false,
  },
  {
    id: 'ripple',
    name: 'XRP',
    symbol: 'xrp',
    price: 0.52,
    change: '+1.05%',
    up: true,
  },
  {
    id: 'cardano',
    name: 'Cardano',
    symbol: 'ada',
    price: 0.38,
    change: '+0.90%',
    up: true,
  },
  {
    id: 'dogecoin',
    name: 'Dogecoin',
    symbol: 'doge',
    price: 0.09,
    change: '-0.30%',
    up: false,
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'dot',
    price: 7.8,
    change: '+2.00%',
    up: true,
  },
  {
    id: 'tron',
    name: 'TRON',
    symbol: 'trx',
    price: 0.1,
    change: '+0.40%',
    up: true,
  },
  {
    id: 'polygon',
    name: 'Polygon',
    symbol: 'matic',
    price: 0.75,
    change: '-0.80%',
    up: false,
  },
  {
    id: 'litecoin',
    name: 'Litecoin',
    symbol: 'ltc',
    price: 95,
    change: '+1.10%',
    up: true,
  },
  {
    id: 'shiba-inu',
    name: 'Shiba Inu',
    symbol: 'shib',
    price: 0.000025,
    change: '+0.50%',
    up: true,
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    symbol: 'avax',
    price: 35,
    change: '-1.40%',
    up: false,
  },
  {
    id: 'chainlink',
    name: 'Chainlink',
    symbol: 'link',
    price: 14,
    change: '+3.20%',
    up: true,
  },
  {
    id: 'stellar',
    name: 'Stellar',
    symbol: 'xlm',
    price: 0.12,
    change: '+0.70%',
    up: true,
  },
  {
    id: 'uniswap',
    name: 'Uniswap',
    symbol: 'uni',
    price: 6.5,
    change: '-0.20%',
    up: false,
  },
  {
    id: 'cosmos',
    name: 'Cosmos',
    symbol: 'atom',
    price: 8.2,
    change: '+1.80%',
    up: true,
  },
  {
    id: 'monero',
    name: 'Monero',
    symbol: 'xmr',
    price: 165,
    change: '-0.50%',
    up: false,
  },
  {
    id: 'bitcoin-cash',
    name: 'Bitcoin Cash',
    symbol: 'bch',
    price: 250,
    change: '+0.60%',
    up: true,
  },
  {
    id: 'vechain',
    name: 'VeChain',
    symbol: 'vet',
    price: 0.03,
    change: '+2.00%',
    up: true,
  },
  {
    id: 'apecoin',
    name: 'ApeCoin',
    symbol: 'ape',
    price: 1.5,
    change: '-1.00%',
    up: false,
  },
  {
    id: 'algorand',
    name: 'Algorand',
    symbol: 'algo',
    price: 0.22,
    change: '+1.50%',
    up: true,
  },
  {
    id: 'hedera',
    name: 'Hedera',
    symbol: 'hbar',
    price: 0.08,
    change: '+0.80%',
    up: true,
  },
  {
    id: 'the-sandbox',
    name: 'The Sandbox',
    symbol: 'sand',
    price: 0.35,
    change: '-0.90%',
    up: false,
  },
  {
    id: 'decentraland',
    name: 'Decentraland',
    symbol: 'mana',
    price: 0.4,
    change: '+1.25%',
    up: true,
  },
];
